## County Health Data ReadMe

##### The purpose of this file is to outline how to use the County Health Data and explain how these steps can be reproduced.

Import the Pandas and Numpy packages in order to use and manipulate the data from the .csv file.

Pandas and Numpy can be imported using the following command:

In [1]:
import pandas as pd
import numpy as np

Once the information above has been typed, select the shift and return button on the keyboard. Utilizing these two buttons runs the code.

Pandas is abbreviated to "pd" so "pandas" does not have to be written everytime it needs to be utilized. The same situation occurs with Numpy, which is abbreviated to "np".

After Pandas and Numpy have been imported, the .csv file containing the data must be read. This is necessary in order to utilize the data. The CountyHealthData_2014-2015.csv will be read using Pandas (pd) and be defined as "df". Defining this removes the requirement of inserting the full name of the file everytime. 

CountyHealthData_2014-2015.csv can be defined using the following command:

In [2]:
df=pd.read_csv("CountyHealthData_2014-2015.csv")

In [28]:
Object1="Monday"
Object2="Tuesday"
Object3="Wednesday"
Object4="Thursday"
Object5="Friday"
WeekDays=(Object1, Object2, Object3, Object4, Object5)

In [29]:
print(WeekDays)

('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')

**Bolded text**

*Italics*

In [3]:
df.shape

(6109, 64)

In [4]:
df.size

390976

In [5]:
df.size == 6109*64

True

In [6]:
df.columns

Index(['State', 'Region', 'Division', 'County', 'FIPS', 'GEOID', 'SMS Region',
       'Year', 'Premature death', 'Poor or fair health',
       'Poor physical health days', 'Poor mental health days',
       'Low birthweight', 'Adult smoking', 'Adult obesity',
       'Food environment index', 'Physical inactivity',
       'Access to exercise opportunities', 'Excessive drinking',
       'Alcohol-impaired driving deaths', 'Sexually transmitted infections',
       'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists',
       'Mental health providers', 'Preventable hospital stays',
       'Diabetic screening', 'Mammography screening', 'High school graduation',
       'Some college', 'Unemployment', 'Children in poverty',
       'Income inequality', 'Children in single-parent households',
       'Social associations', 'Violent crime', 'Injury deaths',
       'Air pollution - particulate matter', 'Drinking water violations',
       'Severe housing problems', 'Driving alone to work',
       'Long commute - driving alone', '2011 population estimate',
       'Population that is not proficient in English',
       'Population living in a rural area', 'Diabetes', 'HIV prevalence rate',
       'Premature age-adjusted mortality', 'Infant mortality',
       'Child mortality', 'Food insecurity', 'Limited access to healthy foods',
       'Motor vehicle crash deaths', 'Drug poisoning deaths',
       'Uninsured adults', 'Uninsured children', 'Health care costs',
       'Could not see doctor due to cost', 'Other primary care providers',
       'Median household income', 'Children eligible for free lunch',
       'Homicide rate', 'Inadequate social support'],
      dtype='object')

In [7]:
df.dtypes

State                                object
Region                               object
Division                             object
County                               object
FIPS                                  int64
                                     ...
Other primary care providers        float64
Median household income               int64
Children eligible for free lunch    float64
Homicide rate                       float64
Inadequate social support           float64
Length: 64, dtype: object

In [8]:
df.State.value_counts()

TX    469
GA    318
VA    266
KY    240
MO    229
IL    204
NC    200
KS    199
IA    198
TN    190
IN    184
OH    176
MN    174
MI    164
MS    163
NE    157
OK    154
AR    150
WI    144
FL    134
PA    134
AL    134
LA    128
NY    124
CO    119
SD    117
CA    114
WV    110
ND     92
MT     92
SC     92
ID     84
WA     78
OR     67
NM     64
UT     54
MD     48
AK     46
WY     46
NJ     42
NV     32
ME     32
AZ     30
MA     28
VT     28
NH     20
CT     16
RI     10
HI      8
DE      6
DC      1
Name: State, dtype: int64

In [9]:
print(df.Region.dtypes)

object

In [10]:
df.Region.value_counts()

South        2803
Midwest      2038
West          834
Northeast     434
Name: Region, dtype: int64

In [20]:
df.sample(n=10)

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
132,AL,South,East South Central,Macon County,1087,1087,Region 16,1/1/2014,13906.0,0.247,...,NaN,0.195,0.044,7801.0,0.151,73.0,27709,0.981,28.67,0.191
142,AL,South,East South Central,Mobile County,1097,1097,Region 16,1/1/2014,10188.0,0.226,...,11.62,0.239,0.055,10102.0,0.186,53.0,39546,0.629,14.05,0.244
4693,SD,Midwest,West North Central,Moody County,46101,46101,Insuff Data,1/1/2015,5538.0,0.190,...,NaN,0.177,0.078,8788.0,NaN,16.0,53712,0.291,NaN,NaN
135,AL,South,East South Central,Madison County,1089,1089,Region 16,1/1/2015,7579.0,0.141,...,7.36,0.174,0.038,9835.0,0.125,63.0,58258,0.310,5.50,NaN
2688,MN,Midwest,West North Central,Nicollet County,27103,27103,Insuff Data,1/1/2015,4924.0,0.077,...,6.17,0.078,0.045,7709.0,NaN,42.0,58620,0.545,NaN,NaN
1514,IL,Midwest,East North Central,Randolph County,17157,17157,Region 25,1/1/2014,6887.0,0.116,...,8.08,0.142,0.030,10022.0,NaN,39.0,46817,0.377,NaN,0.197
1005,GA,South,South Atlantic,Stewart County,13259,13259,Insuff Data,1/1/2015,10575.0,NaN,...,NaN,0.259,0.087,9632.0,NaN,102.0,28304,0.853,NaN,NaN
1361,IL,Midwest,East North Central,Alexander County,17003,17003,Insuff Data,1/1/2015,9062.0,NaN,...,NaN,0.179,0.027,9034.0,NaN,26.0,30141,NaN,NaN,NaN
1367,IL,Midwest,East North Central,Brown County,17009,17009,Region 6,1/1/2015,4387.0,NaN,...,NaN,0.139,0.029,8691.0,NaN,44.0,46522,0.184,NaN,NaN
3940,NY,Northeast,Mid-Atlantic,Schenectady County,36093,36093,Region 14,1/1/2014,5907.0,0.154,...,5.16,0.131,0.042,7500.0,0.054,76.0,54654,0.307,4.51,0.136

In [19]:
df.County.value_counts()

Washington County       60
Jefferson County        50
Franklin County         48
Lincoln County          46
Jackson County          44
                        ..
Dickens County           1
Issaquena County         1
District of Columbia     1
Golden Valley County     1
Aurora County            1
Name: County, Length: 1830, dtype: int64

In [3]:
df["State"][5:10]

5    AK
6    AK
7    AK
8    AK
9    AK
Name: State, dtype: object

In [5]:
df[["State","Year","County","Uninsured adults"]][19:25]

   State      Year                      County  Uninsured adults
19    AK  1/1/2015       Kodiak Island Borough             0.320
20    AK  1/1/2014  Lake and Peninsula Borough             0.434
21    AK  1/1/2015  Lake and Peninsula Borough             0.406
22    AK  1/1/2014   Matanuska-Susitna Borough             0.266
23    AK  1/1/2015   Matanuska-Susitna Borough             0.254
24    AK  1/1/2014            Nome Census Area             0.373

In [6]:
df.iloc[5010,55]

0.281

In [7]:
df.iloc[:,3]

0       Aleutians West Census Area
1       Aleutians West Census Area
2                Anchorage Borough
3                Anchorage Borough
4               Bethel Census Area
                   ...
6104                  Uinta County
6105               Washakie County
6106               Washakie County
6107                 Weston County
6108                 Weston County
Name: County, Length: 6109, dtype: object

In [8]:
df.iloc[0:3,:]

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
0,AK,West,Pacific,Aleutians West Census Area,2016,2016,Insuff Data,1/1/2014,NaN,0.122,...,NaN,0.374,0.250,3791.0,0.185,216.0,69192,0.127,NaN,0.287
1,AK,West,Pacific,Aleutians West Census Area,2016,2016,Insuff Data,1/1/2015,NaN,0.122,...,NaN,0.314,0.176,4837.0,0.185,254.0,74088,0.133,NaN,NaN
2,AK,West,Pacific,Anchorage Borough,2020,2020,Region 22,1/1/2014,6827.0,0.125,...,15.37,0.218,0.096,6588.0,0.119,135.0,71094,0.319,6.29,0.160

In [9]:
df.loc[0:3,"State"]

0    AK
1    AK
2    AK
3    AK
Name: State, dtype: object

In [11]:
df.loc[0:3,["State","County","Division"]]

  State                      County Division
0    AK  Aleutians West Census Area  Pacific
1    AK  Aleutians West Census Area  Pacific
2    AK           Anchorage Borough  Pacific
3    AK           Anchorage Borough  Pacific

In [12]:
df[df["State"] == "RI"]

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
4505,RI,Northeast,New England,Bristol County,44001,44001,Region 12,1/1/2014,4543.0,0.087,...,12.35,0.113,0.027,8579.0,0.077,18.0,64572,0.139,NaN,0.197
4506,RI,Northeast,New England,Bristol County,44001,44001,Region 12,1/1/2015,3891.0,0.087,...,11.67,0.110,0.044,8355.0,0.077,16.0,68415,0.155,NaN,NaN
4507,RI,Northeast,New England,Kent County,44003,44003,Region 12,1/1/2014,6313.0,0.122,...,15.55,0.110,0.027,9890.0,0.105,61.0,59682,0.223,1.44,0.187
4508,RI,Northeast,New England,Kent County,44003,44003,Region 12,1/1/2015,6458.0,0.122,...,18.94,0.114,0.046,9621.0,0.105,68.0,63232,0.230,1.30,NaN
4509,RI,Northeast,New England,Newport County,44005,44005,Region 12,1/1/2014,4457.0,0.109,...,12.29,0.119,0.033,8897.0,0.090,30.0,63434,0.222,NaN,0.176
4510,RI,Northeast,New England,Newport County,44005,44005,Region 12,1/1/2015,4730.0,0.109,...,10.33,0.118,0.048,8149.0,0.090,33.0,67291,0.230,NaN,NaN
4511,RI,Northeast,New England,Providence County,44007,44007,Region 12,1/1/2014,6468.0,0.154,...,15.67,0.190,0.049,9480.0,0.125,88.0,47601,0.484,4.10,0.229
4512,RI,Northeast,New England,Providence County,44007,44007,Region 12,1/1/2015,6124.0,0.154,...,17.51,0.182,0.058,8983.0,0.125,93.0,47642,0.487,3.70,NaN
4513,RI,Northeast,New England,Washington County,44009,44009,Region 12,1/1/2014,4961.0,0.092,...,10.56,0.105,0.031,8776.0,0.088,39.0,69150,0.172,NaN,0.157
4514,RI,Northeast,New England,Washington County,44009,44009,Region 12,1/1/2015,4939.0,0.092,...,13.18,0.107,0.047,8212.0,0.088,49.0,69267,0.177,NaN,NaN

In [13]:
RI_subset = df[df["State"] == "RI"].copy()

In [14]:
RI_subset

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
4505,RI,Northeast,New England,Bristol County,44001,44001,Region 12,1/1/2014,4543.0,0.087,...,12.35,0.113,0.027,8579.0,0.077,18.0,64572,0.139,NaN,0.197
4506,RI,Northeast,New England,Bristol County,44001,44001,Region 12,1/1/2015,3891.0,0.087,...,11.67,0.110,0.044,8355.0,0.077,16.0,68415,0.155,NaN,NaN
4507,RI,Northeast,New England,Kent County,44003,44003,Region 12,1/1/2014,6313.0,0.122,...,15.55,0.110,0.027,9890.0,0.105,61.0,59682,0.223,1.44,0.187
4508,RI,Northeast,New England,Kent County,44003,44003,Region 12,1/1/2015,6458.0,0.122,...,18.94,0.114,0.046,9621.0,0.105,68.0,63232,0.230,1.30,NaN
4509,RI,Northeast,New England,Newport County,44005,44005,Region 12,1/1/2014,4457.0,0.109,...,12.29,0.119,0.033,8897.0,0.090,30.0,63434,0.222,NaN,0.176
4510,RI,Northeast,New England,Newport County,44005,44005,Region 12,1/1/2015,4730.0,0.109,...,10.33,0.118,0.048,8149.0,0.090,33.0,67291,0.230,NaN,NaN
4511,RI,Northeast,New England,Providence County,44007,44007,Region 12,1/1/2014,6468.0,0.154,...,15.67,0.190,0.049,9480.0,0.125,88.0,47601,0.484,4.10,0.229
4512,RI,Northeast,New England,Providence County,44007,44007,Region 12,1/1/2015,6124.0,0.154,...,17.51,0.182,0.058,8983.0,0.125,93.0,47642,0.487,3.70,NaN
4513,RI,Northeast,New England,Washington County,44009,44009,Region 12,1/1/2014,4961.0,0.092,...,10.56,0.105,0.031,8776.0,0.088,39.0,69150,0.172,NaN,0.157
4514,RI,Northeast,New England,Washington County,44009,44009,Region 12,1/1/2015,4939.0,0.092,...,13.18,0.107,0.047,8212.0,0.088,49.0,69267,0.177,NaN,NaN

In [15]:
df[df["State"] == "NC"].copy()

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
3243,NC,South,South Atlantic,Alamance County,37001,37001,Region 20,1/1/2014,7123.0,0.192,...,10.48,0.259,0.073,8640.0,0.167,46.0,41394,0.444,4.94,0.202
3244,NC,South,South Atlantic,Alamance County,37001,37001,Region 20,1/1/2015,7291.0,0.192,...,12.38,0.249,0.088,9050.0,0.167,56.0,43001,0.455,4.60,NaN
3245,NC,South,South Atlantic,Alexander County,37003,37003,Region 20,1/1/2014,7974.0,0.178,...,22.74,0.240,0.077,9316.0,0.205,30.0,39655,0.417,6.27,0.273
3246,NC,South,South Atlantic,Alexander County,37003,37003,Region 20,1/1/2015,8079.0,0.178,...,24.04,0.239,0.076,9242.0,0.205,32.0,46064,0.449,7.20,NaN
3247,NC,South,South Atlantic,Alleghany County,37005,37005,Insuff Data,1/1/2014,8817.0,0.234,...,18.18,0.320,0.131,9585.0,0.210,55.0,34046,0.523,NaN,0.215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3438,NC,South,South Atlantic,Wilson County,37195,37195,Region 20,1/1/2015,8028.0,0.159,...,7.31,0.262,0.079,9450.0,0.107,77.0,40772,0.556,9.60,NaN
3439,NC,South,South Atlantic,Yadkin County,37197,37197,Region 20,1/1/2014,7893.0,0.207,...,18.45,0.252,0.097,10084.0,0.158,32.0,40012,0.422,3.76,0.241
3440,NC,South,South Atlantic,Yadkin County,37197,37197,Region 20,1/1/2015,7258.0,0.207,...,20.21,0.242,0.094,10998.0,0.158,32.0,40998,0.455,NaN,NaN
3441,NC,South,South Atlantic,Yancey County,37199,37199,Region 15,1/1/2014,6872.0,0.193,...,20.79,0.268,0.110,7707.0,0.158,79.0,36019,0.477,NaN,0.176
3442,NC,South,South Atlantic,Yancey County,37199,37199,Region 15,1/1/2015,8917.0,0.193,...,28.02,0.246,0.091,7870.0,0.158,74.0,35866,0.469,NaN,NaN